### ISSUE TITLE
No such file or directory: substrate_node_template_runtime.compact.wasm

### ISSUE THREAD

**Issue by attente** [paritytech/substrate-node-template#10]
Hi, I got this error while running through the tutorial at https://substrate.readme.io/docs/creating-a-custom-substrate-chain (Debian 9.6 (stretch)):

```Compiling substrate-network v0.1.0 (https://github.com/paritytech/substrate#3a8a3925)
   Compiling substrate-service v0.3.0 (https://github.com/paritytech/substrate#3a8a3925)
   Compiling substrate-consensus-aura v0.1.0 (https://github.com/paritytech/substrate#3a8a3925)
   Compiling substrate-finality-grandpa v0.1.0 (https://github.com/paritytech/substrate#3a8a3925)
   Compiling substrate-cli v0.3.0 (https://github.com/paritytech/substrate#3a8a3925)
error: couldn't read src/../runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime.compact.wasm: No such file or directory (os error 2)
  --> src/chain_spec.rs:79:10
   |
79 |             code: include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime.compact.wasm").to_vec(),
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read src/../runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime.compact.wasm: No such file or directory (os error 2)
  --> src/service.rs:24:2
   |
24 |     include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/substrate_node_template_runtime.compact.wasm")
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to 2 previous errors

error: Could not compile `substrate-node-template`.
```

**Comment by attente** [comment]
Looks like it's because runtime/wasm/build.sh is supposed to build that file using wasm-gc. Is that script supposed to run during the build process?

Tangentially, wasm-gc is an archived project since the rust compiler has that functionality as well.

**Comment by bkchr** [comment]
@attente did you run `./init.sh && ./build.sh`?

**Comment by shawntabrizi** [comment]
If you run the command `substrate-node-new substrate-node-template <author-name>` per the instructions on the tutorial, it should run the following script:

https://github.com/paritytech/substrate-up/blob/master/substrate-node-new

which includes:

```
echo "${bold}Initialising webassembly build environment...${normal}"
./init.sh 2>/dev/null >/dev/null

./build.sh
```

My guess is that you run into this error if you directly clone the repository versus using the installation script.

**Comment by shawntabrizi** [comment]
Looks like the issue was related to a problem with the script:
https://github.com/paritytech/substrate-up/pull/7

**Comment by cuiyi0326** [comment]
Hi, I'm following the tutorial and still getting the same error. Is it fixed?

**Comment by shawntabrizi** [comment]
@cuiyi0326 did you check if your `./build.sh` command worked? Did you check that file path for any `.compact.wasm` files that might have a slightly different name?
