### ISSUE TITLE
Substrate Node : Launch of blockchain failed:

### ISSUE THREAD

**Issue by Nayyar525** [paritytech/substrate-node-template#19]
I flow the these steps to make the Substrate up 
Note: I am using Ubuntu machine

1.  run this command in my machine: **_curl https://getsubstrate.io -sSf | bash_**
2. after this i just clone but the git repo. UI and Node Template.
3. After this i am trying to launch the Blockchain . but nothing i am able to do.

Can you please look into this and let me know launch the Blockchain.

**Comment by bkchr** [comment]
Do you get any error message?

**Comment by Nayyar525** [comment]
@bkchr Not able to understand the steps after installing both thr git repo for Node and UI. How to Launch the Blockchain.

**Comment by Nayyar525** [comment]
https://substrate.readme.io/docs/ 

This one. check quick start and Tutorials

**Comment by bkchr** [comment]
@shawntabrizi any idea here?

**Comment by shawntabrizi** [comment]
@Nayyar525 try these steps line by line in your terminal. You can skip the first line if you have already successfully run the "get substrate" command:

```
curl https://getsubstrate.io -sSf | bash
substrate-node-new substrate-example nayyar525
cd substrate-example
./target/release/substrate-example --dev
```

This should start a node. All we are doing here is copying down the substrate-node-template and compiling it (that is what substrate-node-new does), and then we run the binary located in the `.target/release/` folder.

There are step by step instructions you should be able to follow here: https://substrate.readme.io/v1.0.0/docs/creating-a-custom-substrate-chain
