### ISSUE TITLE
build fails, substrate trunk has changed

### ISSUE THREAD

**Issue by warner** [paritytech/substrate-node-template#5]
It looks like the `substrate` repo has moved some things around and changed some APIs, so `substrate-node-template` no longer builds.

I made a start on updating things to match in our branch: https://github.com/Agoric/substrate-node-template/tree/match-new-substrate . But it's not complete yet.. there's a new `ClientWithApi` type in the service that I'm not sure whether I should implement directly, or find something to import.

(I'm still getting my feet wet with this repo, so I may have done something wrong, feel free to ignore my branch in favor of something more idiomatic)

**Comment by shawntabrizi** [comment]
Hey Brian, I just found this issue. Unfortunately I fixed it up in my own branch when I ran into issues earlier today. Wish I would have saw yours, would have saved me a little time :)

https://github.com/paritytech/substrate-node-template/tree/sr-api-remove

**Comment by bkchr** [comment]
Fixed :) Thanks @shawntabrizi for the work.

**Comment by warner** [comment]
Thanks!

I just did a pull to cff9bead5da, deleted Cargo.lock, and re-ran `cargo build`, and got the following error:

```
error[E0277]: `RA` cannot be sent between threads safely
   --> /home/warner/.cargo/git/checkouts/substrate-7e08433d4c370a21/214b687/core/rpc/src/state/mod.rs:117:23
    |
117 | impl<B, E, Block, RA> StateApi<Block::Hash> for State<B, E, Block, RA> where
    |                       ^^^^^^^^^^^^^^^^^^^^^ `RA` cannot be sent between threads safely
    |
    = help: within `client::Client<B, E, Block, RA>`, the trait `std::marker::Send` is not implemented for `RA`
    = help: consider adding a `where RA: std::marker::Send` bound
    = note: required because it appears within the type `std::marker::PhantomData<RA>`
    = note: required because it appears within the type `client::Client<B, E, Block, RA>`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Arc<client::Client<B, E, Block, RA>>`
    = note: required because it appears within the type `state::State<B, E, Block, RA>`

error[E0277]: `RA` cannot be shared between threads safely
   --> /home/warner/.cargo/git/checkouts/substrate-7e08433d4c370a21/214b687/core/rpc/src/state/mod.rs:117:23
    |
117 | impl<B, E, Block, RA> StateApi<Block::Hash> for State<B, E, Block, RA> where
    |                       ^^^^^^^^^^^^^^^^^^^^^ `RA` cannot be shared between threads safely
    |
    = help: within `client::Client<B, E, Block, RA>`, the trait `std::marker::Sync` is not implemented for `RA`
    = help: consider adding a `where RA: std::marker::Sync` bound
    = note: required because it appears within the type `std::marker::PhantomData<RA>`
    = note: required because it appears within the type `client::Client<B, E, Block, RA>`
    = note: required because of the requirements on the impl of `std::marker::Sync` for `std::sync::Arc<client::Client<B, E, Block, RA>>`
    = note: required because it appears within the type `state::State<B, E, Block, RA>`

   Compiling substrate-test-client v0.1.0 (https://github.com/paritytech/substrate#214b687d)
error: aborting due to 2 previous errors
```

Did upstream `substrate` move on us again?

**Comment by warner** [comment]
I get the same error running `cargo build` on a `substrate` checkout, of course, so I suppose technically it's an upstream problem.

**Comment by bkchr** [comment]
Yeah that is a substrate problem, something was merged that should not have been merged! We already work on fixing that, sorry for the inconvenience!
